openapi: 3.0.0
info:
  version: 1.0.0
  title: OpenStack GPU Service
  description: Specification for REST-API of OpenStack Flavor GPU Info.
  license:
    name: Apache License 2.0
paths:
  /gpus/flavors:
    get:
      summary: List all Flavors with used/free GPUs count
      responses:
        401:
          $ref: '#/components/responses/UnauthorizedError'
        200:
          description: A List of all available Flavors with GPUs with used and free GPU slots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlavorGPU"
  /gpus:
    get:
      summary: List all GPUs with free and used Slots
      responses:
        401:
          $ref: '#/components/responses/UnauthorizedError'
        200:
          description: A List of all available Flavors with GPUs with used and free GPU slots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GPU"
  /gpus/{type}:
    get:
      summary: Get specific GPU with free and used Slots
      parameters:
        - in: path
          name: type
          required: true
          schema:
            type: string
      responses:
        404:
          description: Not found
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/404'


        401:
          $ref: '#/components/responses/UnauthorizedError'
        200:
          description: Specific GPU with used and free Slots
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/GPU"
  
  /gpus/flavors/{flavor_openstack_id}:
    get:
      summary: Get specific Flavor with Info of used/free GPU count
      parameters:
        - in: path
          name: flavor_openstack_id
          required: true
          schema:
            type: string
      responses:
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        200:
          description: Flavor with specific Openstack Id with used/free GPU count
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/FlavorGPU"


        
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  schemas:
    404:
      properties:
        message:
          type: string
    GPU:
      properties:
                      type:
                        type: string
                      used_slots:
                        type: number
                      free_slots:
                        type: number
                      total_slots:
                        type: number
    FlavorGPU:
      properties:
                      flavor_openstack_id:
                        type: string
                      flavor_name:
                        type: string
                      gpu:
                        $ref: "#/components/schemas/GPU"
                        
                      
security:
  - basicAuth: [] 
