openapi: 3.0.0
info:
  version: 1.0.0
  title: OpenStack GPU Service
  description: Specification for REST-API of OpenStack Flavor GPU Info.
  license:
    name: Apache License 2.0
paths:
  /gpus/flavors:
    get:
      summary: List all GPU-Flavors with count
      responses:
        401:
          $ref: '#/components/responses/UnauthorizedError'
        200:
          description: A List of all GPU-Flavors with available and total GPU slots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlavorGPU"

  /gpus/flavors/{flavor_openstack_id}:
    get:
      summary: Get specific GPU-Flavor with Info of available and total GPU count
      parameters:
        - in: path
          name: flavor_openstack_id
          required: true
          schema:
            type: string
      responses:
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        200:
          description: GPU-Flavor with specific Openstack Id with available and total GPU count
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/FlavorGPU"


        
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  schemas:
    404:
      properties:
        message:
          type: string
    FlavorGPU:
      properties:
                      flavor_openstack_id:
                        type: string
                      flavor_name:
                        type: string
                      available:
                        type: number
                      total:
                        type: number
                        
                      
security:
  - basicAuth: [] 
