""" Auto generated by OpenAPI Generator (https://openapi-generator.tech). """
import connexion

from openapi_server import encoder


def app():
    app = connexion.App(__name__, specification_dir='./openapi/') # pylint: disable=W0621
    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('openapi.yaml',
                arguments={'title': 'OpenStack GPU Service'},
                pythonic_params=True)
    return app
