#!/usr/bin/env python3
"""
Auto generated by OpenAPI Generator (https://openapi-generator.tech).
"""

from openapi_server import app

if __name__ == '__main__':
    app = app()
    app.run(port=8080)
